# Generated by Django 5.0.3 on 2024-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='email',
            field=models.EmailField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='formdata',
            name='name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
