# Generated by Django 5.0.4 on 2024-05-01 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websiteapp', '0004_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sr',
        ),
    ]
